package cmd

import (
	"fmt"
	"os"

	"github.com/quorum/quorum/internal/exitcodes"
	"github.com/spf13/cobra"
)

const initTemplate = `# Quorum project configuration (generated by quorum init).
package: quorum-tiny
version: 1.0.0
repo: https://github.com/example/tiny
commit: abc123
artifact: tiny-1.0.0.tar.gz
policy:
  policyId: policy-a
  version: v1
  minBuilders: 2
  requiredAgreement: 2
  requiredIndependentGroups: 2
`

func newInitCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "init [--dir DIR] [--force]",
		Short: "Scaffold a quorum.yaml project file",
		RunE: func(cmd *cobra.Command, args []string) error {
			dir, _ := cmd.Flags().GetString("dir")
			force, _ := cmd.Flags().GetBool("force")
			if dir == "" {
				dir = "."
			}
			path := dir + "/quorum.yaml"
			if _, err := os.Stat(path); err == nil && !force {
				if !useJSON(cmd) {
					fmt.Fprintf(cmd.ErrOrStderr(), "error: %s exists (use --force to overwrite)\n", path)
				}
				return &exitErr{code: exitcodes.InvalidInput}
			}
			if err := os.WriteFile(path, []byte(initTemplate), 0o600); err != nil {
				fmt.Fprintf(cmd.ErrOrStderr(), "error: %v\n", err)
				return &exitErr{code: exitcodes.Operational}
			}
			return emit(cmd, fmt.Sprintf("initialized %s\n", path), map[string]string{"path": path})
		},
	}
	c.Flags().String("dir", ".", "target directory")
	c.Flags().Bool("force", false, "overwrite existing quorum.yaml")
	return c
}
